name: Test github action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to use
        required: true
        type: environment

jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: ${{github.event.input.environment}}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Print stuff
        run: |
          echo $VAR_1
          echo ${{github.event.input.environment}}
