name: Test github action
run-name: Enviroment ${{inputs.environment}} by @${{github.actor}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to use
        required: true
        type: environment

jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Print stuff
        run: |
          echo VAR_1 = $VAR_1
          echo vars.VAR_1=${{ vars.VAR_1 }}
          echo ${{inputs.environment}}
